name = "dinamicas-worker"
compatibility_date = "2026-01-14"
main = "index.js"

[durable_objects]
bindings = [
  { name = "REGISTRO_DO", class_name = "RegistroDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["RegistroDO"]
